/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MultiTransfer__factory } from "./MultiTransfer__factory";
export { TestL3P__factory } from "./TestL3P__factory";
