/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MultiTransfer__factory } from "./MultiTransfer__factory";
export { TestToken__factory } from "./TestToken__factory";
